<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Galerie</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">
                    <div class="image-slider fotorama" data-allowfullscreen="true" data-width="100%" data-ratio="16/9" data-maxwidth="100%" data-nav="thumbs" data-fit="cover">
                        <img src="includes/images/960x540/expedice.jpg">
                        <img src="includes/images/960x540/vecere.jpg">
                        <img src="includes/images/960x540/polednik.jpg">
                        <img src="includes/images/960x540/hlavy.jpg">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>