<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Galerie</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
        <div class="column gallery col-sm-6 col-md-3">
            <div class="content-box">
                <div class="section-content gallery">
                    <a href="/galerie/1-obrazek"><img class="img img-responsive" src="../../includes/images/480x270/photo.png" alt="Fotografie" title="Description"></a>
                </div>
            </div>
        </div>
    </div>
</div>