<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Galerie</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single image">
            <div class="content-box">
                <div class="section-content">
                    <img class="img img-responsive" src="/includes/images/fullsize/image.png" alt="Fotografie" title="" />
                </div>
            </div>
        </div>
    </div>
</div>