<div class="page-heading">
    <h1>Přidat novou galerii</h1>
</div>

<div class="section">
    <div class="column single">
        <div class="content-box">
            <form role="form" enctype="multipart/form-data" id="new_gallery" action="/administrace/galerie/vytvorit" method="post">
                <div class="col-lg-6 col-lg-offset-3">
                    <div class="form-group">
                        <label for="title">Název galerie</label>
                        <input class="form-control" type="text" name="title" placeholder="Zadejte název galerie" id="title" required>
                        <input type="hidden" name="author" value="<?= $_SESSION["user"]->getId() ?>">
                    </div>
                </div>
                
                <div class="col-lg-6 col-lg-offset-3">
                    <div class="form-group">
                        <label for="croppbox-input">Fotografie</label>
                        <input class="croppbox-gallery-input btn btn-default" name="img[]" multiple="multiple" type="file" id="croppbox-input">
                        <div id="croppbox"></div>
                    </div>
                </div>
                
                <div class="col-lg-6 col-lg-offset-3">
                    <div class="form-group">
                        <input class="form-control" type="submit" name="save" value="Vytvořit" id="add">
                    </div>
                </div>
                
                <div class="col-lg-6 col-lg-offset-3">
                    <div id="image-holder">
                    
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>