<div class="page-heading">
    <h1>Seznam komentářů k článku číslo <?= $data["article_id"] ?></h1>
</div>

<?php if(!$data["comments"]->isEmpty()): ?>
<div class="section">
    <div class="column single">
        <div class="content-box">
            <table class="table table-bordered table-striped comment-list">
                <thead>
                    <tr>
                        <th>Obsah komentáře</th>
                        <th>Autor</th>
                        <th class="text-center">Datum</th>
                        <th class="text-center">Odstranit</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data["comments"] as $comment): ?>
                    <tr>
                        <td class="col-xs-7">
                            <?= $comment->getContent() ?>
                        </td>
                        <td class="col-xs-2">
                            <a class="list" href="/profil/<?= $comment->getUser()->getUrl() ?>">
                                <?= $comment->getUser()->getUsername() ?>
                            </a>
                        </td>
                        <td class="text-center col-xs-2">
                            <?= $comment->getCreatedAt()->format("d.m.Y H:i:s") ?>
                        </td>
                        <td class="text-center col-xs-1">
                            <a class="list" href="/administrace/clanek/<?= $data["article_id"] ?>/komentar/<?= $comment->getId() ?>/odstranit">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php endif; ?>