<div class="page-heading">
    <h1>Upravit článek</h1>
</div>

<div class="section">
    <div class="column single">
        <div class="content-box">
            <form role="form" action="/administrace/clanky/ulozit" method="post">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="title">Nadpis článku</label>
                        <input class="form-control" type="text" name="title" placeholder="Zadejte nadpis článku" id="title" value="<?= $data["article"]->getTitle() ?>" required>
                        <input type="hidden" name="article" value="<?= $data["article"]->getId() ?>">
                    </div>
                    <div class="form-group">
                        <label for="keywords">Klíčová slova</label>
                        <input class="form-control" type="text" name="keywords" placeholder="Zadejte klíčová slova článku" id="keywords" value="<?= $data["article"]->getKeywords() ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="category">Kategorie</label>
                        <select class="form-control" name="category" id="category">
                            <?php foreach($data["categories"] as $category): ?>
                            <option <?= $category->getId()==$data["article"]->getCategory()->getId() ? "selected='selected'" : "" ?> value="<?= $category->getId() ?>"><?= $category->getName() ?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
                
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="content">Obsah článku</label>
                        <textarea class="form-control" name="content" id="content">
                            <?= $data["article"]->getContent() ?>
                        </textarea>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-lg btn-default pull-left" type="submit" name="save" value="Upravit" id="add">
                    </div>
                </div>
                
                <div class="col-lg-6">
                    <div class="form-group">
                        <div id="croppbox"></div>
                        <label for="croppbox-input">Fotografie (nová)</label>
                        <input class="btn btn-default" name="img" type="file" id="croppbox-input">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>