<div class="page-heading">
    <h1>Seznam galerií</h1>
</div>

<?php if(isset($data["galleries"])): ?>
<div class="section">
    <div class="column single">
        <div class="content-box gallery-list">
            <?php foreach($data["galleries"] as $gal): ?>
            <div class="col-xs-6 col-sm-4 col-md-3 item">
                <div class="inner">
                    <?php $images = $gal->getImages() ?>
                    <a href="/administrace/galerie/<?= $gal->getId() ?>">
                        <img src="/includes/images/fullsize/<?= $images[0]->getPath() ?>" alt="" title="" class="img img-responsive">
                    </a>
                    <h4 class="text-center"><?= $gal->getName() ?></h4>
                </div>
            </div>
            <?php endforeach; ?>
            <div class="col-xs-6 col-sm-4 col-md-3 item">
                <div class="inner">
                    <a href="/administrace/galerie/pridat">
                        <img src="/includes/images/add.png" alt="" title="" class="img img-responsive">
                    </a>
                    <h4 class="text-center">Přidat novou galerii</h4>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>