<div class="section">
    <div class="page-heading">
        <h1>Hlavní stránka administrace</h1>
    </div>
</div>

<div class="section">
    <div class="column">
        <div class="content-box">
            <div class="admin-news">
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/co-je-noveho/uzivatele">
                        <div class="content">
                            <div class="icon physical">
                                <span class="glyphicon glyphicon-user"></span>
                            </div>
                            <div class="text">
                                Noví uživatelé: <span class="badge"><?= $data["new"]["users"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/co-je-noveho/komentare">
                        <div class="content">
                            <div class="icon skills">
                                <span class="glyphicon glyphicon-comment"></span>
                            </div>
                            <div class="text">
                                Nové komentáře: <span class="badge"><?= $data["new"]["comments"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/co-je-noveho/clanky">
                        <div class="content">
                            <div class="icon volunteering">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </div>
                            <div class="text">
                                Nové články: <span class="badge"><?= $data["new"]["articles"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/co-je-noveho/fotografie">
                        <div class="content">
                            <div class="icon expedition">
                                <span class="glyphicon glyphicon-picture"></span>
                            </div>
                            <div class="text">
                                Nové fotografie <span class="badge"><?= $data["new"]["images"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/chyby/vyresene">
                        <div class="content">
                            <div class="icon solved">
                                <i class="fa fa-bug"></i>
                            </div>
                            <div class="text">
                                Vyřešené chyby <span class="badge"><?= $data["new"]["solved_bugs"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/chyby/nevyresene">
                        <div class="content">
                            <div class="icon unsolved">
                                <i class="fa fa-exclamation"></i>
                            </div>
                            <div class="text">
                                Nevyřešené chyby <span class="badge"><?= $data["new"]["unsolved_bugs"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/nahlaseni-uzivatele">
                        <div class="content">
                            <div class="icon report">
                                <i class="fa fa-flag"></i>
                            </div>
                            <div class="text">
                                Nahlášení uživatelé <span class="badge"><?= $data["new"]["user_reports"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <a class="detail-link" href="/administrace/navrhy/neschvalene">
                        <div class="content">
                            <div class="icon gold">
                                <i class="fa fa-lightbulb-o"></i>
                            </div>
                            <div class="text">
                                Neschválené návrhy <span class="badge"><?= $data["new"]["ideas"] ?></span>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>