<div class="section">
    <div class="page-heading">
        <h1>Hlavní stránka administrace</h1>
    </div>
</div>

<div class="section">
    <div class="column">
        <div class="content-box">
            <div class="admin-news">
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon physical">
                            <button class="icon" type="button">
                                <span class="glyphicon glyphicon-user"></span>
                            </button>
                        </div>
                        <div class="text">
                            Noví uživatelé: <span class="badge"><?= $data["new"]["users"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon skills">
                            <button class="icon" type="button">
                                <span class="glyphicon glyphicon-comment"></span>
                            </button>
                        </div>
                        <div class="text">
                            Nové komentáře: <span class="badge"><?= $data["new"]["comments"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon volunteering">
                            <button class="icon" type="button">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </button>
                        </div>
                        <div class="text">
                            Nové články: <span class="badge"><?= $data["new"]["articles"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon expedition">
                            <button class="icon" type="button">
                                <span class="glyphicon glyphicon-picture"></span>
                            </button>
                        </div>
                        <div class="text">
                            Nové fotografie <span class="badge"><?= $data["new"]["images"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon solved">
                            <button class="icon" type="button">
                                <i class="fa fa-bug"></i>
                            </button>
                        </div>
                        <div class="text">
                            Vyřešené chyby <span class="badge"><?= $data["new"]["solved_bugs"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon unsolved">
                            <button class="icon" type="button">
                                <i class="fa fa-exclamation"></i>
                            </button>
                        </div>
                        <div class="text">
                            Nevyřešené chyby <span class="badge"><?= $data["new"]["unsolved_bugs"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon report">
                            <button class="icon" type="button">
                                <i class="fa fa-flag"></i>
                            </button>
                        </div>
                        <div class="text">
                            Nahlášení uživatelé <span class="badge"><?= $data["new"]["user_reports"] ?></span>
                        </div>
                    </div>
                </div>
                <div class="news-item col-sm-6 col-lg-3">
                    <div class="content">
                        <div class="icon physical">
                            <button class="icon" type="button">
                                <i class="fa fa-lightbulb-o"></i>
                            </button>
                        </div>
                        <div class="text">
                            Návrhy <span class="badge"><?= $data["new"]["ideas"] ?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>