<div class="content">    
    <div class="section">
        <div class="page-heading register">
            <h1>Registrační formulář</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">    
                    <form class="register col-xs-offset-1 col-xs-10" role="form" action="/registrovat" method="post">
                        <div class="form-group">
                            <label for="regUsername">Uživatelské jméno</label>
                            <input class="form-control" id="regUsername" type="text" name="regUsername" placeholder="Zadejte prosím uživatelské jméno." required autofocus />
                        </div>
                        <div class="form-group">
                            <label for="regPassword">Heslo (8-32 znaků)</label>
                            <input class="form-control" id="regPassword" type="password" name="regPassword" placeholder="Zadejte prosím heslo." required />
                        </div>
                        <div class="form-group">
                            <label for="regPassword2">Heslo znovu</label>
                            <input class="form-control" id="regPassword2" type="password" name="regPassword2" placeholder="Zadejte prosím heslo znovu." required />
                        </div>
                        <div class="form-group">
                            <label for="regEmail">Email</label>
                            <input class="form-control" id="regEmail" type="email" name="regEmail" placeholder="Zadejte prosím email." required />
                        </div>

                        <div class="form-group">
                            <input class="btn btn-default" type="submit" name="register" value="Registrovat" >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>