<div class="content">    
    <div class="section">
        <div class="page-heading register">
            <h1>Zapomenuté heslo</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">    
                    <form class="register col-xs-offset-1 col-xs-10" role="form" action="/zapomenute-heslo-email" method="post">
                        <div class="form-group">
                            <label for="forgPw">Uživatelské jméno nebo emailová adresa</label>
                            <input class="form-control" id="forgPw" type="text" name="forgPw" placeholder="Zadejte prosím uživatelské jméno nebo emailovou adresu." required autofocus />
                        </div>

                        <div class="form-group">
                            <input class="btn btn-default" type="submit" name="forgottenPassword" value="Vyhledat účet" >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>