<div class="content">    
    <div class="section">
        <div class="page-heading register">
            <h1>Podat návrh</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">    
                    <form class="register col-xs-offset-1 col-xs-10" role="form" action="/nastaveni/navrh-zlepseni" method="post">
                        <div class="form-group">
                            <label for="description">Návrh</label>
                            <textarea class="form-control no-resize" rows="8" id="description" name="description" placeholder="Popište nám do detailu svůj návrh." required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="reason">Důvod</label>
                            <textarea class="form-control no-resize" rows="6" id="reason" name="reason" placeholder="Proč bychom měli Váš návrh uskutečnit?" required></textarea>
                        </div>
                        
                        <div class="form-group">
                            <input class="btn btn-default" type="submit" name="report" value="Navrhnout" >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>