<div class="content">
    <div class="section">
        <div class="column single">
            <div class="section-content profile">
                <div class="col-xs-4 side">
                    <div class="image">
                        <img class="img-thumbnail img img-responsive" src="includes/images/200x200/profilepic01.png" alt="Profilový obrázek" title="Profilový obrázek uživatele aaaaaaa" >
                    </div>
                    <div class="menu">
                        aaa
                    </div>
                </div>
                <div class="col-xs-8 info">
                    <h1>Martin Brom</h1>
                    aaa
                </div>
            </div>
        </div>
    </div>
</div>