<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Nahlášení aktivit</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-header smaller log-dofe">
                    <h2><a class="pull-left" href="/nahlasit-aktivitu">&lt;&lt;</a>Datum...<a class="pull-right" href="/nahlasit-aktivitu">&gt;&gt;</a></h2>
                </div>
                <div class="section-content log-dofe">
                    <form class="log-dofe" role="form" method="post" action="/ulozit-aktivitu">
                        <div class="form-group">
                            <input type="checkbox" name="activity" value="skill"> Rozvoj talentu
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="activity" value="physical"> Sportovní aktivita
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="activity" value="volunteering"> Dobrovolnictví
                        </div>
                        
                        <input class="btn btn-default" type="submit" value="Odeslat" name="log-dofe">
                        <br>
                        <?= "rok: " . $data["date"]["year"] . "<br>" ?>
                        <?= "měsíc: " . $data["date"]["month"] . "<br>" ?>
                        <?= "den: " . $data["date"]["day"] . "<br>" ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>