<div class="content">    
    <div class="section">
        <div class="page-heading register">
            <h1>Zažádat o členství v programu</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">    
                    <form class="register col-xs-offset-1 col-xs-10" role="form" action="/nastaveni/ulozit-zadost-o-clenstvi" method="post">
                        <div class="form-group">
                            <label for="name">Křestní jméno</label>
                            <input class="form-control" type="text" name="name" id="name" placeholder="Zadejte vaše křestní jméno" required/>
                        </div>
                        <div class="form-group">
                            <label for="surname">Příjmení</label>
                            <input class="form-control" type="text" name="surname" id="surname" placeholder="Zadejte vaše příjmení" required/>
                        </div>
                        
                        <div class="form-group">
                            <input class="btn btn-default" type="submit" name="apply" value="Zažádat" >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>