<div class="content">    
    <div class="section">
        <div class="page-heading register">
            <h1>Nové heslo</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">
                    <form role="form" class="register col-xs-offset-1 col-xs-10" method="post" action="/obnoveni-heslo/<?= $data["username"] ?>/<?= $data["token"] ?>">
                        <div class="form-group">
                            <label for="password">Heslo</label>
                            <input type="password" class="form-control" name="password" id="password" placeholder="Zadejte nové heslo" required/>
                        </div>
                        <div class="form-group">
                            <label for="password_again">Ověření hesla</label>
                            <input type="password" class="form-control" name="password_again" id="password_again" placeholder="Zadejte nové heslo podruhé" required/>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="save" value="Uložit" class="btn btn-default"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>