<div class="content">    
    <div class="section">
        <div class="page-heading register">
            <h1>Nahlásit chybu na stránce</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content">    
                    <form class="register col-xs-offset-1 col-xs-10" role="form" action="/nastaveni/nahlasit-chyba" method="post">
                        <div class="form-group">
                            <label for="location">Lokalizace</label>
                            <input class="form-control" type="text" placeholder="Kde jste chybu nalezli?" name="location" id="location" required/>
                        </div>
                        <div class="form-group">
                            <label for="description">Popis chyby</label>
                            <textarea class="form-control no-resize" rows="8" placeholder="Pokud možno, popište chybu co nejpřesněji." name="description" id="description" required></textarea>
                        </div>
                        <div class="form-group">
                            <label for="device">Označení zařízení (pokud možno)</label>
                            <input class="form-control" type="text" placeholder="Na jakém zařízení se chyba vyskytla?" name="device" id="device"/>
                        </div>
                        <div class="form-group">
                            <label for="browser">Webový prohlížeč (pokud možno)</label>
                            <input class="form-control" type="text" placeholder="Jaký jste používali webový prohlížeč?" name="browser" id="browser"/>
                        </div>
                        <div class="form-group">
                            <label for="severity">Závažnost chyby</label>
                            <select name="severity" id="severity" class="form-control">
                                <option value="1">Nízká</option>
                                <option value="2">Střední</option>
                                <option value="3">Vysoká</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <input class="btn btn-default" type="submit" name="report" value="Nahlásit" >
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>