<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Nastavení profilu</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content settings">
                    <div class="personal">
                        <h2 class="settings-heading">OSOBNÍ</h2>
                        <ul class="settings">
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/zmenit-udaje#jmeno"><i class="fa fa-user"></i> Změnit uživatelské jméno</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/zmenit-udaje#heslo"><i class="fa fa-key"></i> Změnit heslo</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/zmenit-udaje#email"><i class="fa fa-envelope"></i> Změnit emailovou adresu</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/zmenit-avatar"><i class="fa fa-image"></i> Změnit profilový obrázek</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="#"><i class="fa fa-users"></i> Zažádat o členství v programu</a>
                            </li>
                        </ul>
                    </div>
                    <div class="dofe">
                        <h2 class="settings-heading">DOFE</h2>
                        <ul class="settings">
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nahlasit-aktivitu"><i class="fa fa-check"></i> Nahlásit aktivitu</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/zmenit-dofe#cil"><i class="fa fa-pencil"></i> Změnit cíl</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/zmenit-dofe#obor"><i class="fa fa-pencil"></i> Změnit obor</a>
                            </li>
                        </ul>
                    </div>
                    <div class="general">
                        <h2 class="settings-heading">OBECNÉ</h2>
                        <ul class="settings">
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/nahlasit-uzivatele"><i class="fa fa-flag"></i> Nahlásit uživatele</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/nahlasit-chybu"><i class="fa fa-bug"></i> Nahlásit chybu na stránce</a>
                            </li>
                            <li class="item col-sm-6 col-lg-4">
                                <a href="/nastaveni/navrhnout-zlepseni"><i class="fa fa-lightbulb-o"></i> Podat návrh na zlepšení</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>