<!DOCTYPE html>
<html>
	<head>
		<base href="/">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
        <meta name="keywords" content="">
		<meta name="author" content="OneTimeCZ">
		<title>DofE | <?= $data["title"] ?></title>
		<script src="includes/scripts/jquery-1.11.3.js"></script>
		<script src="includes/scripts/bootstrap.min.js"></script>
        <?php if(isset($data["js"]))foreach($data["js"] as $js): ?>
        <script src="includes/<?= $js ?>.js"></script>
        <?php endforeach; ?>
		<link rel="shortcut icon" type="image/png" href="includes/images/favicon.png"/>
		<link rel="stylesheet" type="text/css" href="includes/css/bootstrap.min.css" />
        <?php if(isset($data["css"]))foreach($data["css"] as $css): ?>
            <link rel="stylesheet" type="text/css" href="includes/<?= $css ?>.css" />
        <?php endforeach; ?>
        <link rel="stylesheet" type="text/css" href="includes/css/font-awesome.min.css" />
		<link rel="stylesheet" type="text/css" href="includes/css/style.css" />
	</head>
	<body>
        <div class="page-container">
            <div class="content">
                <div class="container-fluid">
                    <div class="admin_side_nav col-sm-2">
                        <div class="navbar-header">
                            <a href="/administrace">Administrace</a>
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#admin_navbar" aria-expanded="false">
                                <span class="sr-only">Přepnout navigaci</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="admin_navbar">
                            <ul class="navigation">
                                <li class="profile">
                                    <p>Jste přihlášeni jako: </p>
                                    <a href="/profil/<?= $_SESSION["user"]->getUrl() ?>">
                                        <img class="img img-responsive" src="../includes/images/50x50/<?= $_SESSION["user"]->getImage()->getThumbnailPath() ?>">
                                        <?= $_SESSION["user"]->getUsername() ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="/">ZPĚT NA HLAVNÍ STRÁNKU</a>
                                </li>                            
                                <li <?= $data['active'] == 'addArticle' ? 'class = active' : '' ?>>
                                    <a href="/administrace/clanky/pridat">PŘIDAT ČLÁNEK</a>
                                </li>
                                <li <?= $data['active'] == 'list' ? 'class = active' : '' ?>>
                                    <a href="/administrace/clanky">SEZNAM ČLÁNKŮ</a>
                                </li>
                                <li <?= $data['active'] == 'addPhoto' ? 'class = active' : '' ?>>
                                    <a href="/administrace/fotografie/nahrat">PŘIDAT FOTOGRAFIE</a>
                                </li>
                                <li <?= $data['active'] == 'addGallery' ? 'class = active' : '' ?>>
                                    <a href="/administrace/galerie/pridat">PŘIDAT GALERII</a>
                                </li>
                                <li <?= $data['active'] == 'galleryList' ? 'class = active' : '' ?>>
                                    <a href="/administrace/galerie">SEZNAM GALERIÍ</a>
                                </li>
                                <li <?= $data['active'] == 'users' ? 'class = active' : '' ?>>
                                    <a href="/administrace/uzivatele">ZMĚNIT PRÁVA</a>
                                </li>
                                <li>
                                    <a href="/odhlasit">ODHLÁSIT SE</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="admin_main col-sm-10">
                        <div class="content">
                            <?php if(!empty($data["popups"])): ?>
                                <?php foreach($data["popups"] as $f): ?>
                                    <?php require 'popup.phtml'; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php require_once $view . '.phtml'; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</body>
</html>