<div class="page-heading">
    <h1>Seznam článků</h1>
</div>

<div class="section">
    <div class="column single">
        <div class="content-box">
            <?php if(!isset($data["articles"])): ?>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>Ale ne!</strong> V databázi se momentálně nenachází žádný článek :&#40;
            </div>
            <?php else: ?>
            <table class="table table-bordered table-striped article-list">
                <?php if($_SESSION["user"]->getPermissions() == 3): ?>
                <thead>
                    <tr>
                        <th>Název článku</th>
                        <th>Autor</th>
                        <th class="text-center">Datum</th>
                        <th class="text-center">Upravit</th>
                        <th class="text-center">Odstranit</th>
                        <th class="text-center">Komentáře</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data["articles"] as $article): ?>
                    <tr>
                        <td class="col-xs-5"><?= $article->getTitle() ?></td>
                        <td class="col-xs-2">
                            <a class="list" href="/profil/<?= $article->getUser()->getUrl() ?>">
                                <?= $article->getUser()->getUsername() ?>
                            </a>
                        </td>
                        <td class="col-xs-2 text-center"><?= $article->getCreatedAt()->format("d.m.Y H:i:s") ?></td>
                        <td class="col-xs-1 text-center">
                            <a class="list" href="/administrace/clanek/<?= $article->getId() ?>/upravit">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </td>
                        <td class="col-xs-1 text-center">
                            <a class="list" href="/administrace/clanek/<?= $article->getId() ?>/odstranit">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </td>
                        <td class="col-xs-1 text-center">
                            <a class="list" href="/administrace/clanek/<?= $article->getId() ?>/komentare">
                                <span class="glyphicon glyphicon-comment"></span>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                <?php elseif($_SESSION["user"]->getPermissions() == 2): ?>
                <thead>
                    <tr>
                        <th>Název článku</th>
                        <th class="text-center">Datum</th>
                        <th class="text-center">Upravit</th>
                        <th class="text-center">Komentáře</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($data["articles"] as $article): ?>
                    <tr>
                        <td class="col-xs-8"><?= $article->getTitle() ?></td>
                        <td class="col-xs-3 text-center"><?= $article->getCreatedAt()->format("d.m.Y H:i:s") ?></td>
                        <td class="col-xs-1 text-center">
                            <a class="list" href="/administrace/clanek/<?= $article->getId() ?>/upravit">
                                <span class="glyphicon glyphicon-pencil"></span>
                            </a>
                        </td>
                        <td class="col-xs-1 text-center">
                            <a class="list" href="/administrace/clanek/<?= $article->getId() ?>/komentare">
                                <span class="glyphicon glyphicon-comment"></span>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
                <?php endif; ?>
            </table>
            <?php endif; ?>
        </div>
    </div>
</div>