<div class="content">   
    <div class="section">
        <div class="section-header">
            VYHLEDÁVÁNÍ
        </div>
        <div class="section-content">   
            <div class="input-group search col-md-12">
                <input type="text" class="  search-query form-control" placeholder="Vyhledávání" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class=" glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </div>     
    </div>
    
    <div class="section">
        <div class="section-header">
            NEJNOVĚJŠÍ
        </div>
        <div class="section-content">
            <ul class="article-recent">
                <li class="article">
                    <a href="" class="thumbnail">
                        <img src="" alt="" title="" />
                    </a>
                    <div class="info">
                        <a href="/clanek/1-test-clanek" class="title">Nadpis článku</a>
                        <div class="meta">
                            <p>Datum | <a class="category" href="/clanky/kategorie">Kategorie</a></p>
                        </div>
                    </div>
                </li>
                <li class="article">
                    <a href="" class="thumbnail">
                        <img src="" alt="" title="" />
                    </a>
                    <div class="info">
                        <a href="/clanek/1-test-clanek" class="title">Nadpis článku</a>
                        <div class="meta">
                            <p>Datum | <a class="category" href="/clanky/kategorie">Kategorie</a></p>
                        </div>
                    </div>
                </li>
                <li class="article">
                    <a href="" class="thumbnail">
                        <img src="" alt="" title="" />
                    </a>
                    <div class="info">
                        <a href="/clanek/1-test-clanek" class="title">Nadpis článku</a>
                        <div class="meta">
                            <p>Datum | <a class="category" href="/clanky/kategorie">Kategorie</a></p>
                        </div>
                    </div>
                </li>
                <li class="article">
                    <a href="" class="thumbnail">
                        <img src="" alt="" title="" />
                    </a>
                    <div class="info">
                        <a href="/clanek/1-test-clanek" class="title">Nadpis článku</a>
                        <div class="meta">
                            <p>Datum | <a class="category" href="/clanky/kategorie">Kategorie</a></p>
                        </div>
                    </div>
                </li>
                <li class="article">
                    <a href="" class="thumbnail">
                        <img src="" alt="" title="" />
                    </a>
                    <div class="info">
                        <a href="/clanek/1-test-clanek" class="title">Nadpis článku</a>
                        <div class="meta">
                            <p>Datum | <a class="category" href="/clanky/kategorie">Kategorie</a></p>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    
    <div class="section">
        <div class="section-header">
            SLEDUJTE NÁS
        </div>
        <div class="section-content">
            social network stuffs
        </div>
    </div>
</div>