<div class="content">   
    <div class="section">
        <div class="section-header">
            VYHLEDÁVÁNÍ
        </div>
        <div class="section-content">   
            <div class="input-group search col-md-12">
                <input type="text" class="  search-query form-control" placeholder="Vyhledávání" />
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class=" glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </div>
        </div>     
    </div>
    
    <div class="section">
        <div class="section-header">
            NEJNOVĚJŠÍ
        </div>
        <div class="section-content">
            <?php if(isset($data["recent"])): ?>
            <ul class="article-recent">
                <?php foreach($data["recent"] as $recent): ?>
                <li class="article">
                    <a href="/clanek/<?= $recent->getId() ?>" class="thumbnail">
                        <img src="../includes/images/50x50/<?= $recent->getImage()->getPath() ?>" alt="" title="" />
                    </a>
                    <div class="info">
                        <a href="/clanek/<?= $recent->getId() ?>" class="title"><?= $recent->getTitle() ?></a>
                        <div class="meta">
                            <p>
                                <?= $recent->getCreatedAt()->format("d.m.Y") ?> | 
                                <a href="<?= $recent->getCategory()->getUrl() ?>"><?= $recent->getCategory()->getName() ?></a>
                            </p>
                        </div>
                    </div>
                </li>
                <?php endforeach; ?>
            </ul>
            <?php else: ?>
            <div class="alert alert-danger alert-dismissible" role="alert">
                <strong>Ale ne!</strong> V databázi se momentálně nenachází žádný článek :&#40;
            </div>
            <?php endif; ?>
        </div>
    </div>
    
    <div class="section">
        <div class="section-header">
            SLEDUJTE NÁS
        </div>
        <div class="section-content">
            social stuffs
        </div>
    </div>
</div>