<footer class="col-xs-12">
    <div class="container-fluid col-lg-offset-1 col-lg-10">
        <div class="content">
            <div class="section footer-list">
                <h4>Důležité odkazy</h4>
                <ul class="footer-list">
                    <li>
                        <a href="http://www.dofe.org"></a>
                    </li>
                    <li>
                        <a href="http://www.dofe.cz"></a>
                    </li>
                    <li>
                        <a href="http://"></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>