<footer class="col-xs-12">
    <div class="container-fluid col-lg-offset-1 col-lg-10">
        <div class="content">
            <div class="section footer-list">
                <ul class="footer-list col-sm-4 text-center">
                    <h4>Důležité odkazy</h4>
                    <li>
                        <a href="http://www.dofe.org">Mezinárodní stránka DofE</a>
                    </li>
                    <li>
                        <a href="http://www.dofe.cz">DofE Česká Republika</a>
                    </li>
                    <li>
                        <a href="http://www.spseplzen.cz">VOŠ a SPŠE Plzeň</a>
                    </li>
                </ul>
                
                <ul class="footer-list col-sm-4 text-center">
                    <h4>Mapa stránek</h4>
                    <li>
                        <a href="/galerie">Galerie</a>
                    </li>
                    <li>
                        <a href="/clanky">Blog</a>
                    </li>
                    <li>
                        <a href="/informace">Informace</a>
                    </li>
                    <li>
                        <a href="/registrace">Založit účet</a>
                    </li>
                </ul>
                
                <ul class="footer-list col-sm-4 text-center">
                    <h4>Pro účastníky</h4>
                    <li>
                        <a href="/nahlasit-aktivitu">Nahlašování aktivit</a>
                    </li>
                    <li>
                        <a href="/nastaveni">Nastavení profilu</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>