<nav class="navbar navbar-inverse navigation">
    <div class="container-fluid col-md-offset-1 col-md-10">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle menu" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>
            <a href="/"><img src="../includes/images/logo-dofe-gray.png" title="DofE logo" alt="DofE logo"></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navigation search visible-xs">
                <li>
                    <div class="input-group search col-md-12">
                        <input type="text" class="  search-query form-control" placeholder="Vyhledávání" />
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class=" glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </li>
            </ul>
            <ul class="nav navbar-nav navigation">
                <li <?= $data['active'] == 'gallery' ? 'class = active' : '' ?> >
                    <a class="border" href="/galerie">GALERIE</a>
                </li>
                <li <?= $data['active'] == 'blog' ? 'class = active' : '' ?> >
                    <a class="border" href="/clanky">BLOG</a>    
                </li>
                <?php if(isset($_SESSION["user"]) && $_SESSION["user"]->getPermissions() >= 2): ?>
                <li <?= $data['active'] == 'admin' ? 'class = active' : '' ?> >
                    <a class="border" href="/administrace">ADMINISTRACE</a>    
                </li>
                <?php endif; ?>
            </ul>
            <ul class="nav navbar-nav navigation login-menu login-box navbar-right">
                <li <?= $data['active'] == 'profile' ? 'class = active' : '' ?> >
                    <?php if (!isset($_SESSION['user'])): ?>
                        <a class="border" data-toggle="modal" data-target="#login_modal" href="#">PŘIHLÁSIT SE</a>
                    <?php else: ?>
                        <!-- Mobile phone -->
                        <div class="visible-xs">
                            <a class="borderless" href="/profil/<?= $_SESSION["user"]->getUrl() ?>">
                                <img alt="profilepic" class="img img-responsive avatar" src="../includes/images/50x50/<?= $_SESSION["user"]->getImage()->getPath() ?>">
                            </a>
                            <a class="menu-item" href="/profil/<?= $_SESSION["user"]->getUrl() ?>">
                                VÁŠ PROFIL
                            </a>
                            <div class="divider"></div>
                            <a class="menu-item" href="#">
                                NASTAVENÍ
                            </a>
                            <a class="menu-item pull-right" href="/odhlasit">
                                ODHLÁSIT SE
                            </a>
                        </div>
                        <!-- Tablet, PC -->
                        <div class="dropdown hidden-xs">
                            <button class="borderless dropdown-toggle" type="button" data-toggle="dropdown">
                                <img alt="profilepic" class="img img-responsive avatar" src="../includes/images/50x50/<?= $_SESSION["user"]->getImage()->getPath() ?>">
                            </button>
                            <ul class="dropdown-menu">
                                <li class="header">
                                    <?= $_SESSION["user"]->getUsername() ?>
                                </li>
                                <li class="divider"></li>
                                <li><a href="#">Váš Profil</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Nastavení</a></li>
                                <li class="divider"></li>
                                <li><a href="/odhlasit">Odhlásit</a></li>
                            </ul>
                        </div>
                    <?php endif; ?>
                </li>        
            </ul>
        </div>
    </div>
</nav>