<nav class="navbar navbar-inverse navigation">
    <div class="container-fluid col-md-offset-1 col-md-10">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle menu" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
            </button>
            <a href="/"><img src="../includes/images/logo-dofe-gray.png" title="DofE logo" alt="DofE logo"></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navigation">
                <li <?php $class = $data['active'] == 'gallery' ? 'class = active' : ''; echo $class; ?> >
                    <a class="border" href="/galerie">GALERIE</a>
                </li>
                <li <?php $class = $data['active'] == 'blog' ? 'class = active' : ''; echo $class; ?> >
                    <a class="border" href="/clanky">BLOG</a>    
                </li>
            </ul>
            <ul class="nav navbar-nav navigation login-box navbar-right">
                <li>
                    <?php if (!isset($_SESSION['user'])): ?>
                        <a class="border" data-toggle="modal" data-target="#login_modal" href="#">PŘIHLÁSIT SE</a>
                    <?php else: ?>
                        <!-- SQL profile picture -->
                        <a class="borderless" href="/profil"><img alt="profilepic" class="img img-responsive" src="../includes/images/32x32/profilepic.png"><p>&nbsp;&nbsp;USERNAME</p></a>
                    <?php endif; ?>
                </li>        
            </ul>
        </div>
    </div>
</nav>