<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Blog - strana: <?= $data['page'] ?></h1>
        </div>
    </div>
    
    <div class="section">
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header image">
                    <div class="thumbnail">
                        <img src="../../includes/images/960x540/expedice.png" alt="" title="" />
                    </div>
                </div>
                <div class="section-content post">
                    <h2 class="title">Nadpis článku</h2>
                    <div class="meta">
                        <p>
                            Autor:
                            <a href="/profil/Username" rel="author" title="Profil uživatele Insert a username">Insert a username</a>
                            | Datum |
                            <a href="/clanky/kategorie">Kategorie</a>      
                        </p>
                    </div>
                    <div class="description">
                        <p class="description">
                            Bacon ipsum dolor amet meatloaf frankfurter tongue shoulder ham, beef ribs pork sirloin...
                        </p>
                    </div>
                    <a class="read_more btn btn-default" href="/clanek/1-test-clanku">Více...</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header image">
                    <div class="thumbnail">
                        <img src="../../includes/images/960x540/vyhled_polednik.png" alt="" title="" />
                    </div>
                </div>
                <div class="section-content post">
                    <h2 class="title">Nadpis článku</h2>
                    <div class="meta">
                        <p>
                            Autor:
                            <a href="/profil/Username" rel="author" title="Profil uživatele Insert a username">Insert a username</a>
                            | Datum |
                            <a href="/clanky/kategorie">Kategorie</a>      
                        </p>
                    </div>
                    <div class="description">
                        <p class="description">
                            Bacon ipsum dolor amet meatloaf frankfurter tongue shoulder ham, beef ribs pork sirloin...
                        </p>
                    </div>
                    <a class="read_more btn btn-default" href="/clanek/1-test-clanku">Více...</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header image">
                    <div class="thumbnail">
                        <img src="../../includes/images/960x540/hlavy.png" alt="" title="" />
                    </div>
                </div>
                <div class="section-content post">
                    <h2 class="title">Nadpis článku</h2>
                    <div class="meta">
                        <p>
                            Autor:
                            <a href="/profil/Username" rel="author" title="Profil uživatele Insert a username">Insert a username</a>
                            | Datum |
                            <a href="/clanky/kategorie">Kategorie</a>      
                        </p>
                    </div>
                    <div class="description">
                        <p class="description">
                            Bacon ipsum dolor amet meatloaf frankfurter tongue shoulder ham, beef ribs pork sirloin...
                        </p>
                    </div>
                    <a class="read_more btn btn-default" href="/clanek/1-test-clanku">Více...</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header image">
                    <div class="thumbnail">
                        <img src="../../includes/images/960x540/vecere.png" alt="" title="" />
                    </div>
                </div>
                <div class="section-content post">
                    <h2 class="title">Nadpis článku</h2>
                    <div class="meta">
                        <p>
                            Autor:
                            <a href="/profil/Username" rel="author" title="Profil uživatele Insert a username">Insert a username</a>
                            | Datum |
                            <a href="/clanky/kategorie">Kategorie</a>      
                        </p>
                    </div>
                    <div class="description">
                        <p class="description">
                            Bacon ipsum dolor amet meatloaf frankfurter tongue shoulder ham, beef ribs pork sirloin...
                        </p>
                    </div>
                    <a class="read_more btn btn-default" href="/clanek/1-test-clanku">Více...</a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content pagination">
                    <ul>
                        <li>
                            <a href="/clanky">
                                <span>&laquo;</span> Novější
                            </a>
                        </li>
                        <li>
                            <a href="/clanky">
                                Starší <span>&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>