<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Blog - strana: <?= $data['page'] ?></h1>
        </div>
    </div>
    
    <div class="section">
    <?php foreach($data["articles"] as $article): ?>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header image">
                    <div class="thumbnail">
                        <img src="../../includes/images/960x540/<?= $article->getImage()->getPath() ?>" alt="" title="" />
                    </div>
                </div>
                <div class="section-content post">
                    <h2 class="title"><?= $article->getTitle() ?></h2>
                    <div class="meta">
                        <p>
                            Autor:
                            <a href="/profil/<?= $article->getUser()->getUrl() ?>" rel="author" title="Profil uživatele <?= $article->getUser()->getUsername() ?>"><?= $article->getUser()->getUsername() ?></a>
                            | <?= $article->getCreatedAt()->format("d.m.Y H:i:s") ?> |
                            <a href="/clanky/<?= $article->getCategory()->getUrl() ?>"><?= $article->getCategory()->getName() ?></a>
                        </p>
                    </div>
                    <div class="description">
                        <p class="description">
                            <?= substr(strip_tags($article->getContent()), 0, 250)."..." ?>
                        </p>
                    </div>
                    <a class="read_more btn btn-default" href="/clanek/<?= $article->getUrl() ?>">Více...</a>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="content-box">
                <div class="section-content pagination">
                    <ul>
                        <li>
                            <a href="/clanky">
                                <span>&laquo;</span> Novější
                            </a>
                        </li>
                        <li>
                            <a href="/clanky">
                                Starší <span>&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>