<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1><?= $data["article"]->getTitle() ?></h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column">
            <div class="section-header image">
                <div class="thumbnail">
                    <img src="../../includes/images/fullsize/<?= $data["article"]->getImage()->getPath() ?>" alt="" title="" />
                </div>
            </div>
            <div class="section-content post article">
                <div class="meta">
                    <p>
                        Autor:
                        <a href="/profil/<?= $data["article"]->getUser()->getUrl() ?>" rel="author" title="Profil uživatele <?= $data["article"]->getUser()->getUsername() ?>"><?= $data["article"]->getUser()->getUsername() ?></a>
                        | <?= $data["article"]->getCreatedAt()->format("d.m.Y H:i:s") ?> |
                        <a href="/clanky/<?= $data["article"]->getCategory()->getUrl() ?>"><?= $data["article"]->getCategory()->getName() ?></a>      
                    </p>
                </div>
                <div class="text">
                    <p class="text">
                        <?= $data["article"]->getContent() ?>
                    </p>
                </div>
            </div>    
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <?php if($data["comments"] != NULL): ?>
            <div class="section-header comments">
                Komentáře
            </div>
            <?php endif;
            ?>
            <div class="section-content comments" id="komentare">
                <ul class="comments">
                    <?php
                    if(isset($data["comments"])) {
                    foreach ($data["comments"] as $comment): ?>
                               
                    <li class="comment">
                        <div class="avatar">
                            <a href="/profil/<?= $comment->getUser()->getUrl() ?>">
                                <img src="../../includes/images/50x50/<?= $comment->getUser()->getImage()->getPath() ?>" alt="profilový obrázek" title="Profil uživatele <?= $comment->getUser()->getUsername() ?>" />
                            </a>
                        </div>
                        <div class="info">
                            <a href="/profil/<?= $comment->getUser()->getUrl() ?>">
                                <h4><?= $comment->getUser()->getUsername() ?></h4>
                            </a>
                            <p><?= $comment->getCreatedAt()->format("d.m.Y H:i:s") ?></p>
                            <p class="pull-right rating">
                                <?php $likes = 0; foreach($comment->getRatings() as $rating){if($rating->getType() == 1)$likes++;} echo $likes; ?> <button class="rating like"><i class="fa fa-thumbs-up"></i></button>&nbsp;
                                <?php $dislikes = 0; foreach($comment->getRatings() as $rating){if($rating->getType() == 0)$dislikes++;} echo $dislikes; ?> <button class="rating dislike"><i class="fa fa-thumbs-down"></i></button>
                            </p>
                        </div>
                        <div class="content_area">
                            <p class="comment">
                                <?= $comment->getContent() ?>
                        </div>
                    </li>

                    <?php endforeach;
                    }

                    if(isset($_SESSION["user"])): ?>
                    <li class="comment_form">
                        <div class="comment_form">
                            <h3 class="heading">Sdílejte svůj názor</h3>
                            <form class="comment_form" role="form" action="/clanek/<?= $data["article"]->getId() ?>/komentovat" method="post">
                                <textarea placeholder="Text komentáře" name="comment_text" id="comtxt" required ></textarea>
                                <input type="submit" value="Okomentovat" class="comment_submit" name="comment_submit" />
                            </form>
                        </div>
                    </li>
                    <?php else: ?>
                    <li class="comment_help">
                        <h3>Pro okomentování tohoto příspěvku se prosíme přihlašte <a href="#" data-toggle="modal" data-target="#login_modal">zde</a>...</h3>
                    </li>
                    <?php endif;
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>