<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Informace</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="section-header small single">
                <div class="nav-part text-center col-xs-4">
                    <a href="/informace#pro-rodice">Pro rodiče</a>
                </div>
                <div class="nav-part text-center col-xs-4">
                    <a href="/informace#pro-studenty">Pro studenty</a>
                </div>
                <div class="nav-part text-center col-xs-4">
                    <a href="/informace#nas-tym">Náš tým</a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="section-content info">
                <div class="parents">
                
                </div>
                <div class="students">
                
                </div>
                <div class="team">
                
                </div>
            </div>
        </div>
    </div>
</div>