<div class="content">    
    <div class="section">
        <div class="page-heading">
            <h1>Informace</h1>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="section-header small single">
                <div class="nav-part text-center col-xs-4">
                    <a href="/informace#pro-rodice">Pro rodiče</a>
                </div>
                <div class="nav-part text-center col-xs-4">
                    <a href="/informace#pro-studenty">Pro studenty</a>
                </div>
                <div class="nav-part text-center col-xs-4">
                    <a href="/informace#nas-tym">Náš tým</a>
                </div>
            </div>
        </div>
    </div>
    
    <div class="section">
        <div class="column single">
            <div class="section-content info">
                <div class="parents">
                    <div class="heading">
                        <h3 id="pro-rodice">Pro rodiče</h3>
                    </div>
                    <div class="content">
                        <div class="faq-item">
                            <h5 class="question">Co je program DofE?</h5>
                            <p class="answer">
                                Program DofE je vzdělávací program, který mladým lidem od 14 do dovršení 25 let umožňuje rozvíjet své dovednosti a aktivně využívat volný čas. Program DofE je součástí celosvětové prestižní Mezinárodní ceny vévody z Edinburghu a už od roku 1956 podporuje v desítkách zemí po celém světě mladé lidi napříč společností na cestě k jejich samostatnosti, sebevědomí, budoucímu uplatnění i sociálnímu cítění.<br><br>
                                V programu DofE si mladí lidé stanovují individuální cíle a výzvy v několika aktivitách a na cestě k jejich splnění posilují svou zodpovědnost a vytrvalost, poznávají a překonávají sami sebe a získávají nové dovednosti, užitečné pro další studijní i pracovní život. Navíc se zapojením do programu stávají součástí mezinárodní komunity a v případě potřeby mohou získat finanční podporu pro své aktivity.<br><br>
                                Po celém světě se již do programu DofE zapojilo přes osm milionů mladých lidí. V ČR účastníci programu DofE mimo jiné věnují ročně 30 000 hodin komunitě a potřebným v rámci své dobrovolné činnost. V současnosti je do programu DofE v ČR zapojeno přes 600 mladých lidí a 250 dobrovolných mentorů, kteří je na jejich cestě podporují.
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Jaký je význam programu?</h5>
                            <p class="answer">
                                Přínosy a úspěchy programu Mezinárodní cena vévody z Edinburghu (anglickým názvem The Duke of Edinburgh’s International Award, zkráceně DofE Award) jsou už od jeho založení v roce 1956 důkladně sledovány.<br><br>
                                <span class="answer-heading">Rozvoj nových dovedností, které mohou v budoucnu uplatnit (nejen) na trhu práce:</span><br>
                                - Zvýšení sebedůvěry a sebevědomí<br>
                                - Rozvoj samostatnosti a zodpovědnosti za sebe i za druhé<br>
                                - Vytvoření povědomí o vlastním potenciálu, o svých silných i slabších stránkách<br>
                                - Rozvoj schopnosti pracovat ve skupině<br>
                                - Nalezení nových zájmů, přátel a příležitostí<br>
                                - Rozvoj schopnosti efektivně plánovat a rozhodovat se, být zodpovědný a spolehlivý<br>
                                - Možnost dosáhnout ve svém volném čase něčeho pozitivního a konstruktivního<br>
                                - Dobrý pocit z dosažení stanovených cílů a překonání sebe sama<br>
                                - Vytvoření sebemotivujícího a aktivního postoje ke světu kolem sebe<br>
                                - Rozvoj schopnosti učit se z vlastní zkušenosti a zážitku<br>
                                - Společenské ocenění vynaloženého úsilí v podobě certifikátu a jeho slavnostního předání<br><br>
                                Výsledky výzkumů ukázaly, že účast v programu díky těmto přínosům přispívá ke zlepšení školní docházky a prospěchu mladých lidí, vyvoválá v nich celoživotní zájem o vzdělávání, zvyšuje jejich zaměstnatelnost, občanskou aktivitu či toleranci k odlišnostem a hraje důležitou roli také v prevenci asociálního a kriminálního chování.
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Statistiky programu</h5>
                            <p class="answer">
                                - Program je nyní dostupný ve více než 140 zemích světa<br>
                                - Od založení programu v roce 1956 se ho zúčastnilo přes 8 miliónů mladých lidí<br>
                                - Každý den se do programu zapojuje průměrně 1205 nových účastníků<br>
                                - Program úspěšně dokončí průměrně 548 účastníků za den<br>
                                - V roce 2011 účastníci programu přispěli dobrovolnou prací v délce přes 3,9 milionu hodin k rozvoji místních komunit po celém světě<br>
                                - Jen během roku 2011 se do programu zapojilo víc než 890 tisíc mladých lidí<br>
                                - Na poskytování programu mladým lidem se momentálně podílí přes 200 tisíc dobrovolníků
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Kolik to stojí?</h5>
                            <p class="answer">
                                Program DofE je v České republice spravován neziskovou organizací, jejímž hlavním smyslem je dát možnost mladým trávit svůj volný čas smysluplně. Je určen pro všechny, kteří chtějí věnovat čas seberealizaci a pomoci ostatním.<br><br>
                                Proto ti, kteří se chtějí programu DofE účastnit, nemusí platit žádné významné poplatky spjaté se vstupem do programu, jediným nákladem pro mladého člověka zaplacení symbolického poplatku 100 Kč, za který získají účastnickou knížku programu DofE, pravidelnou podporu vyškoleného vedoucího programu a slevovou kartičku EYCA.<br><br>
                                Program DofE nehradí náklady na jednotlivé aktivity, které si mladí lidé pro jeho plnění vyberou (například kroužky, kurzy, sportovní kluby, výbava, cestovné). Pokud by však hrazení těchto nákladů mělo mladému člověku překážet v jeho plnění programu DofE, může jeho vedoucí programu požádat o příspěvek z Fondu DofE ve výši až 1500 Kč na sportovní aktivitu či/a rozvoj talentu a 4000 Kč na dobrodružnou expedici.
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Bezpečnost mládeže</h5>
                            <p class="answer">
                                <span class="answer-heading">Odborné vedení</span><br>
                                O účastníky programu se starají vedoucí, kteří absolvovali minimálně naše základní školení. Kromě informací o principech programu tedy vedoucí disponují znalostmi o různých technikách a aktivitách, hodících se při práci s jednotlivci i skupinou.<br><br>
                                <span class="answer-heading">Ochrana osobních údajů</span><br>
                                Zavazujeme se nakládat s osobními údaji účastníka programu v souladu se Zákonem č. 101/2000 Sb., O ochraně osobních údajů, a to takovým způsobem, aby nemohlo dojít k neoprávněnému zneužití těchto údajů.<br><br>
                                <span class="answer-heading">Pojištění</span><br>
                                Každá skupina zapojená do programu DofE je zodpovědná za své pojištění pro aktivity vykonávané v rámci programu.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="students">
                    <div class="heading">
                        <h3 id="pro-studenty">Pro studenty</h3>
                    </div>
                    <div class="content">
                        <div class="faq-item">
                            <h5 class="question">Co to vlastně je?</h5>
                            <p class="answer">
                                Program DofE je příležitostí, jak získat nové přátele, silné zážitky a užitečné dovednosti. Od jeho založení se programu zúčastnilo už přes osm milionů mladých lidí z celého světa a k nim se můžeš přidat i ty.
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">K čemu mi to bude?</h5>
                            <p class="answer">
                                Možná máš nějaká přání a představy o tom, co bys rád dělal, ale nemůžeš se odhodlat s tím začít. Možná máš zajímavé plány, ale jakmile se něco nedaří, vzdáváš se jich. S DofE půjde všechno líp a bude to i větší zábava!
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Jaké oblasti program Dofe nabízí?</h5>
                            <p class="answer">
                                V programu DofE nestačí dělat jen jednu věc, ale je jich třeba splnit několik. Proto si vybereš aktivitu v každé z následujících oblastí a budeš se jí dlouhodobě věnovat.<br><br>
                                <span class=answer-heading>Rozvoj talentu</span>
                                - Každý v sobě skrýváme jiný talent. V našem programu se proto sám rozhodneš, co chceš zlepšit, nebo se věnuješ tomu, co tě nejvíc baví. Možností je spousta – hra na hudební nástroj, jazyky, keramika, nebo třeba nějaká technická dovednost.<br><br>
                                <span class=answer-heading>Sportovní aktivita</span>
                                - Sportem ku zdraví a pohodě. V této oblasti programu zlepšíš svůj sportovní výkon, fyzickou kondici, poznáš radost z pohybu a naučíš se dbát na zásady zdravého životního stylu. Můžeš se věnovat týmovému sportu a při tom získat nové kamarády či si zvolit sport individuální.<br><br>
                                <span class=answer-heading>Dobrovolnictví</span>
                                - Celý život dáváme a dostáváme. Dobrovolnictví je jedním ze způsobů, jak dávat a dostávat zároveň. Seznámíš se při něm s lidmi, které bys jinak nejspíš nepotkal(a), a naučíš se empatii, toleranci, zodpovědnosti a trpělivosti. Zažiješ také, jaké to je být užitečný/á.<br><br>
                                <span class=answer-heading>Dobrodružná expedice</span>
                                - Za hranice všedních zážitků. Dobrodružná expedice je výzvou k překonání obav z neznámého a příležitostí vyrazit s partou na několik dní objevovat zajímavá místa v České republice i zahraničí. Může pršet, může sněžit, ale dobře připravenou skupinu nic takového nepřekvapí.<br><br>
                                <span class=answer-heading>Akce s pobytem</span>
                                - Všude dobře, nejen doma. Tato aktivita se týká jen účastníků zlaté úrovně programu DofE. Na akci s pobytem se seznámíš s novými kamarády v neznámém prostředí a věnuješ se spolu s nimi zajímavé a smysluplné aktivitě dle svého výběru. Akcí s pobytem může být například tábor, vzdělávací pobyt, výměnný zájezd nebo dobrovolnický projekt v České republice, ale i v zahraničí.
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Jaké úrovně programu DofE nabízí?</h5>
                            <p class="answer">
                                Aby pro tebe bylo absolvování programu DofE  opravdovou výzvou, je důležité, aby sis nastavil(a) odpovídající laťku. Bude-li pro tebe dosažení stanovených cílů příliš lehké, nedosáhneš náležitého uspokojení z jejich splnění. Na druhou stranu příliš těžké výzvy by tě mohly odradit. Proto má program tři úrovně s odlišnou obtížností – bronzovou, stříbrnou a zlatou. Můžeš začít nejlehčí, tedy bronzovou úrovní, nebo se pustit rovnou do úrovně stříbrné či zlaté.<br><br>
                                <span class=answer-heading>Bronzová</span>
                                - Do bronzové úrovně se můžeš zapojit od 14 let. Čekají tě v ní celkem 4 oblasti: rozvoj talentu, sportovní aktivita, dobrovolnictví a dobrodružná expedice. Prvním třem aktivitám se budeš věnovat minimálně po dobu 3 měsíců; navíc si z nich vybereš jednu, v níž si stanovíš náročnější cíl, kterému se budeš věnovat o 3 měsíce déle. Dobrodružná expedice musí trvat aspoň 2 dny a 1 noc. K získání Bronzové ceny vévody z Edinburghu je tedy třeba minimálně 6 měsíců.<br><br>
                                <span class=answer-heading>Stříbrná</span>
                                - Do stříbrné úrovně se můžeš zapojit od 15 let. Čekají tě v ní celkem 4 oblasti: rozvoj talentu, sportovní aktivita, dobrovolnictví a dobrodružná expedice. Prvním třem aktivitám se budeš věnovat minimálně po dobu 6 měsíců; pokud nejsi držitelem Bronzové ceny vévody z Edinburghu, vybereš si z nich navíc jednu, v níž si stanovíš náročnější cíl, kterému se budeš věnovat o 6 měsíců déle. Dobrodružná expedice musí trvat aspoň 3 dny a 2 noci. K získání Stříbrné ceny vévody z Edinburghu je tedy třeba minimálně 6 měsíců v případě držitelů Bronzové ceny a minimálně 12 měsíců v případě, že začneš až touto úrovní.<br><br>
                                <span class=answer-heading>Zlatá</span>
                                - Do zlaté úrovně se můžeš zapojit od 16 let. Čeká tě v ní celkem 5 oblastí: rozvoj talentu, sportovní aktivita, dobrovolnictví, dobrodružná expedice a akce s pobytem. Prvním třem aktivitám se budeš věnovat minimálně po dobu 12 měsíců; pokud nejsi držitelem Stříbrné ceny vévody z Edinburghu, vybereš si z nich navíc jednu, v níž si stanovíš náročnější cíl, kterému se budeš věnovat o 6 měsíců déle. Dobrodružná expedice musí trvat aspoň 3 dny a 2 noci, akce s pobytem nejméně 5 dní a 4 noci. K získání Zlaté ceny vévody z Edinburghu je tedy třeba minimálně 12 měsíců v případě držitelů Stříbrné ceny a minimálně 18 měsíců v případě, že začneš až touto úrovní.
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Jak mohu s programem začít?</h5>
                            <p class="answer">
                                K účasti v programu budeš potřebovat podporu některého z našich místních center. Tu získáš za registrační poplatek 100 Kč spolu s účastnickou knížkou, nezbytnou pro plnění programu. V ceně je také slevová kartička EYCA, která by Tě jinak přišla na 100 Kč. Na cestu programem DofE se můžeš vydat v kterékoli organzaci, v níž na Tebe čeká vyškolený mentor a další mladí lidé zapojení do programu DofE - takzvané místní centrum programu DofE. Najdi si tedy na mapě místní centrum programu DofE a oslov kontaktní osobu. Mapu nalezneš na oficiálních stránkách programu <a href=http://www.dofe.cz/cz/jak-zacit>zde.</a>
                            </p>
                        </div>
                        <div class="faq-item">
                            <h5 class="question">Co mi kromě seberozvoje přinese splnění programu?</h5>
                            <p class="answer">
                                Po úspěšném zvládnutí zvolené úrovně programu DofE tě čeká Bronzová, Stříbrná či Zlatá cena vévody z Edinburghu v podobě certifikátu s mezinárodní platností a odznaku.<br><br>
                                Ceny předávají vždy významné osobnosti z Česka i zahraničí. V minulosti se jednalo například o britského prince Edwarda, britskou velvyslankyni, nejznámějšího českého rybáře Jakub Vágnera, cestovatele Dana Přibáně či první českou horolezkyní, která zdolala Mount Everest, Kláru Kolouchovou.
                                Vzhledem k tomu, že program DofE pochází z Velké Británie a jeho zakladatelem je princ Philip, manžel britské královny, zlatých ceremonií se pravidelně účastní příslušníci britské královské rodiny – v minulosti se absolventi programu DofE osobně setkali kromě prince Edwarda i s princem Charlesem či princeznou Annou.<br><br>
                                Slavnostní předávání se koná minimálně dvakrát za rok vždy na půdě některé významné instituce. Absolventi programu DofE, spolu se svými hosty a rodinnými příslušníky, tak mají zároveň možnost prohlédnout si úchvatné prostory historických a významných budov, jakými jsou například Britské velvyslanectví v Praze, Kongresové centrum Praha či Černínský palác.<br><br>
                                Získání Zlaté, Stříbrné, či Bronzové ceny vévody z Edinburghu má však nespočet dalších výhod. Jednou z nejpřednějších je možnost uplatnění certifikátu v rámci přijímacího řízení na některé ze světových univerzit, především pak ty britské. Úspěšné zvládnutí programu DofE může také zaujmout budoucího zaměstnavatele, jelikož samotný certifikát je dokladem o tom, že máš za sebou poctivou práci na rozvoji vlastních kompetencí.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="team">
                    <div class="heading">
                        <h3 id="nas-tym">Účastníci programu</h3>
                    </div>
                    <div class="content">
                    <?php foreach($data["participants"] as $p): ?>
                        <div class="participant col-xs-6 col-md-4">
                            <a href="/profil/<?= $p->getUrl() ?>">
                                <img class="img img-responsive img-circle" src="includes/images/200x200/<?= $p->getImage()->getPath() ?>" alt="Profilový obrázek" title="<?= $p->getMember()->getName() ?> <?= $p->getMember()->getSurname() ?>">
                            </a>
                            <p class="text-center"><?= $p->getMember()->getName() ?> <?= $p->getMember()->getSurname() ?></p>
                        </div>
                    <?php endforeach; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>