<div class="content">    
    <div class="section">
        <div class="column image-slider">
            <div class="content-box">   
                <div class="section-content">
                    <div class="image-slider">
                        <img class="img img-responsive" src="../../includes/images/960x540/expedice.png" alt="expedice" title="DofE expedice" />
                    </div>
                </div>
            </div>     
        </div>    
    </div>
    <div class="section">
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header striped">
                    <div class="color-stripe volunteering"></div>
                    CO JE TO DOFE?
                </div>
                <div class="section-content about">
                    <ul>
                        <li>
                            <h4><u>Základní popis</u></h4>
                            <p>
                                Program DofE (Duke of Edinburgh) je součástí celosvětové prestižní Mezinárodní ceny vévody z Edinburghu a už od roku 1956 podporuje v desítkách zemí po celém světě 
                                mladé lidi napříč společností na cestě k jejich samostatnosti, sebevědomí, budoucímu uplatnění i sociálnímu cítění.<br><br>

                                V programu DofE si mladí lidé stanovují individuální cíle a výzvy v několika aktivitách a na cestě k jejich splnění posilují svou zodpovědnost a vytrvalost, 
                                poznávají a překonávají sami sebe a získávají nové dovednosti, užitečné pro další studijní i pracovní život. Navíc se zapojením do programu stávají 
                                součástí mezinárodní komunity a v případě potřeby mohou získat finanční podporu pro své aktivity.<br><br>

                                Po celém světě se již do programu DofE zapojilo přes osm milionů mladých lidí. 
                                V ČR účastníci programu DofE mimo jiné věnují ročně 30 000 hodin komunitě a potřebným v rámci své dobrovolné činnost. 
                                V současnosti je do programu DofE v ČR zapojeno přes 600 mladých lidí a 250 dobrovolných mentorů, kteří je na jejich cestě podporují.
                            </p>
                            <a class="btn btn-default" href="/informace">Zjistit více o programu...</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header striped">
                    <div class="color-stripe expedition"></div>
                    ÚČASTNÍCI
                </div>
                <div class="section-content participants">
                    <div class="person">
                        <div class="col-xs-6 col-md-12">
                            <img class="img img-responsive img-circle" src="../../includes/images/200x200/profilepic02.png">
                        </div>
                        
                        <div class="col-xs-6 col-md-12">
                            <blockquote>
                                <p>
                                    Aultmore, brandy sour kahlua glenburgie long island iced tea, el presidente edradour. 
                                    Stolichnaya long island iced tea ramos gin.
                                </p>
                                <footer>
                                    Václav Mašek
                                </footer>
                            </blockquote>
                        </div>
                    </div>    
                    <div class="person">    
                        <div class="col-xs-6 col-md-12">
                            <img class="img img-responsive img-circle" src="../../includes/images/200x200/profilepic01.png">
                        </div>
                        
                        <div class="col-xs-6 col-md-12">
                            <blockquote>
                                <p>
                                    Bacon ipsum dolor amet jowl alcatra ham, ham hock prosciutto pastrami porchetta picanha kevin capicola drumstick chicken spare ribs. 
                                    Beef chuck picanha, tongue shank rump kevin filet mignon boudin porchetta bresaola.
                                </p>
                                <footer>
                                    Martin Brom
                                </footer>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
        </div>    
    </div>
</div>