<div class="content">    
    <div class="section">
        <div class="column">
            <div class="content-box">   
                <div class="section-content">
                    <div class="image-slider">
                        <img class="img img-responsive" src="../../includes/images/960x540/expedice.png" alt="expedice" title="DofE expedice" />
                    </div>
                </div>
            </div>     
        </div>    
    </div>
    <div class="section">
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header striped">
                    <div class="color-stripe volunteering"></div>
                    stuff about dofe
                </div>
                <div class="section-content">
                    content
                </div>
            </div>
        </div>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header striped">
                    <div class="color-stripe expedition"></div>
                    stuff about dofe
                </div>
                <div class="section-content">
                    content
                </div>
            </div>
        </div>    
    </div>
</div>