<div class="content">    
    <div class="section">
        <div class="column single image-slider">
            <div class="content-box">   
                <div class="section-content">
                    <div class="image-slider fotorama" data-loop="true" data-ratio="16/9" data-nav="thumbs" data-fit="cover">
                        <img src="includes/images/960x540/expedice.jpg">
                        <img src="includes/images/960x540/vecere.jpg">
                        <img src="includes/images/960x540/polednik.jpg">
                        <img src="includes/images/960x540/hlavy.jpg">
                    </div>
                </div>
            </div>     
        </div>    
    </div>
    <div class="section">
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header striped">
                    <div class="color-stripe volunteering"></div>
                    CO JE TO DOFE?
                </div>
                <div class="section-content about">
                    <ul>
                        <li>
                            <h4><u>Základní popis</u></h4>
                            <p>
                                Program DofE (Duke of Edinburgh) je součástí celosvětové prestižní Mezinárodní ceny vévody z Edinburghu a už od roku 1956 podporuje v desítkách zemí po celém světě 
                                mladé lidi napříč společností na cestě k jejich samostatnosti, sebevědomí, budoucímu uplatnění i sociálnímu cítění.<br><br>

                                V programu DofE si mladí lidé stanovují individuální cíle a výzvy v několika aktivitách a na cestě k jejich splnění posilují svou zodpovědnost a vytrvalost, 
                                poznávají a překonávají sami sebe a získávají nové dovednosti, užitečné pro další studijní i pracovní život.<br><br>

                                Po celém světě se již do programu DofE zapojilo přes osm milionů mladých lidí. 
                                V současnosti je do programu DofE v ČR zapojeno přes 600 mladých lidí a 250 dobrovolných mentorů, kteří je na jejich cestě podporují.
                            </p>
                            <a class="btn btn-default" href="/informace">Zjistit více o programu...</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <?php if(!$data["users"]->isEmpty()): ?>
        <div class="col-md-6 column double">
            <div class="content-box">
                <div class="section-header striped">
                    <div class="color-stripe expedition"></div>
                    ÚČASTNÍCI
                </div>
                <?php $i = 0; $c = count($data["users"]); foreach($data["users"] as $user): ?>
                <div class="section-content participants <?= $hidden = $i == 0 ? '' : 'hidden' ?>">
                    <div class="person">
                        <div class="col-xs-6 col-md-12">
                            <a href="/profil/<?= $user->getUrl() ?>">
                                <img class="img img-responsive img-circle" src="../../includes/images/200x200/<?= $user->getImage()->getPath() ?>">
                            </a>
                        </div>
                        
                        <div class="col-xs-6 col-md-12">
                            <blockquote>
                                <p>
                                    <?php foreach($user->getMember()->getQuotes() as $quote) echo $quote->getContent() ?>
                                </p>
                                <footer>
                                    <?= $user->getMember()->getName().' '.$user->getMember()->getSurname() ?>
                                </footer>
                            </blockquote>
                        </div>
                        
                        <div class="navigation">
                            <?php if($i!=0): ?><button class="previous">&laquo; Předchozí</button><?php endif; ?>
                            <?php if($i!=$c-1): ?><button class="next">Následující &raquo;</button><?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php $i++; endforeach; ?>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>